# https://github.com/golang-migrate/migrate
DB_USER=
DB_PASSWORD=
DB_NAME=simplebank
DB_URL=postgresql://${DB_USER}:${DB_PASSWORD}@localhost:5432/${DB_NAME}?sslmode=disable

migrate.create:
	@read -p "마이그레이션 이름(ex: create_table, add_cloumn): " name ;\
		migrate create -ext sql -dir db/migration -seq $$name ;\

migrate.up:
	@read -p "적용 단계 입력(미입력시 전체 적용): " step ;\
		migrate -source file:./db/migration -database "$(DB_URL)" up $$step ;\

migrate.down:
	@read -p "롤백 단계 입력(미입력시 전체 롤백): " step ;\
		migrate -source file:./db/migration -database "$(DB_URL)" down $$step ;\

sqlc.gen:
	sqlc generate

mock.gen:
	mockgen -package mockdb -destination db/mock/store.go github.com/yeom-c/golang-simplebank/db/sqlc Store

test:
	go test -v -cover ./...

.PHONY: migrate.create migrate.up migrate.down sqlc.gen mock.gen test
