# https://github.com/golang-migrate/migrate
DB_URL=db종류://유저:비밀번호@연결호스트:포트번호/데이터베이스명?옵션=값

migrate.create:
	@read -p "마이그레이션 이름(ex: create_table, add_cloumn): " name ;\
		migrate create -ext sql -dir db/migration -seq $$name ;\

migrate.up:
	@read -p "적용 단계 입력(미입력시 전체 적용): " step ;\
		migrate -source file:./db/migration -database "${DB_URL}" up $$step ;\

migrate.down:
	@read -p "롤백 단계 입력(미입력시 전체 롤백): " step ;\
		migrate -source file:./db/migration -database "${DB_URL}" down $$step ;\

sqlc.gen:
	sqlc gen

test:
	go test -v -cover ./...

.PHONY: migrate.create migrate.up migrate.down sqlc.gen test