name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
    - name: Go 설치
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: 코드 체크아웃
      uses: actions/checkout@v3

    - name: Makefile 생성
      run: |
          touch Makefile
          cat << 'EOF' > Makefile
          ${{ secrets.MAKEFILE }}
          EOF

    - name: golang-migrate 설치
      run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.17.0/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate.linux-amd64 /usr/bin/migrate
          migrate -version

    - name: DB 마이그레이션
      run: make migrate.up

    - name: Test
      run: make test